duo_client/https_wrapper.py
Previously, the library was attempting to validate the proxy host's domain against Duo's certificate (which fails).  This patch uses self._tunnel_host instead it exists.
=> Support cert validation when using a proxy

MANIFEST.in, setup.cfg
The RPM names of the required packages are different than what they are in pypi (six vs python-six). This change allows for building an RPM with `python setup.py bdist_rpm` and having the RPM requirements be correct.
I'm not sure if this is the best way to resolve this--just how I did it. You may want to continue using `requirements.txt`.
=> Cleaner rpm build

duo_client/admin.py
Initially I overlooked that 'device' was even returned as the output from help(get_authentication_log) had it omitted. This helps make sure that it doesn't happen to anybody else.
=> Add missing 'device' field in returned results doc

duo_client/admin.py, tests/test_admin.py
- Add a method to the adminapi client to return a list of endpoint objects
- Docstring updates for adminapi client update
- Add test to make sure that the correct GET request is made for the get_endpoints call
=> Add a method to return a list of the account's endpoint objects

duo_client/admin.py, tests/test_admin.py
- Add methods for v2 API for getting group details
- Add deprecation warning for v1 API for getting group details
- Adds associated tests for groups adminapi methods
- Normalize "gkey" param name to "group_id"
=> Add v2 group detail Admin API methods and associated tests

duo_client/admin.py, tests/test_admin.py, tests/util.py
Add support for v2 authlog url (now generally available) while still leaving v1 the default option.
```
(duo_client_python)ebarbara-28650:duo_client_python ebarbara$ nose2
................................................
----------------------------------------------------------------------
Ran 48 tests in 0.022s
OK
```
=> Add support for v2 authlog url

.travis.yml, duo_client/auth.py, duo_client/auth_v1.py, duo_client/client.py
Rename the `async` parameter to avoid colliding with the new Python 3.7 keyword.  Thus, expect Python 3.7 to pass on TravisCI.
Be slightly stricter about expecting a Boolean for the new parameter.
Major version bump since this is technically a backwards-incompatible change.
=> Rename async parameter, be stricter about expecting a boolean

duo_client/admin.py, tests/test_admin.py
Ensure backwards compatibility by setting default value for limit to None
=> Make limit optional for admin.get_tokens

duo_client/admin.py, tests/admin/test_groups.py
We missed adding an iterator for `get_group_users`, so add it here. As a side effect, `get_group_users` will now return the full result set, rather than the first 100. Fixes #85 
```
$ nose2
.........................................................................................................................................
----------------------------------------------------------------------
Ran 137 tests in 0.134s
OK
```
=> Add admin get_group_users_iterator and call from get_group_users

duo_client/https_wrapper.py
This file used 2 space indentation instead of 4 like the rest of the
project. It actually caused me to write a bug that took a second to
figure out.
Ran
```
$ autopep8 ~/src/duo_client_python/duo_client/https_wrapper.py --select=E101,E121 --in-place
```
=> Fix indentation inconsistency with https_wrapper

duo_client/client.py, requirements-dev.txt, tests/test_client.py, tests/util.py
If the request is rate limited, this library will now sleep for
a bit and then try again. We use an exponential backoff, so the
request should sleep for 1 second, then 2, then 4, 8, 16, and max
out at 32 seconds.
=> Add backoff and retry when a request is rate limited

.flake8, .travis.yml, README.md, duo_client/client.py, requirements-dev.txt, tests/test_https_wrapper.py
Hi, I'm back with round 2...
To explain some of the changes here:
- Via flake8's config setting `select = DUO` we're only running Dlint rules, as opposed to all flake8's rules. This is because there are a couple hundred flake8 violations, and I didn't want to include fixes in this PR.
- We're excluding `duo_client/https_wrapper.py` from analysis because it's a third-party library. Although note it would have the following violations: `./duo_client/https_wrapper.py:72:34: DUO122 insecure "ssl" module attribute use` and `./duo_client/https_wrapper.py:79:35: DUO122 insecure "ssl" module attribute use`.
Let me know if you'd like anything done differently :+1:
=> Add Dlint to CI

duo_client/client.py, tests/test_client.py
Converts booleans and ints to lower case strings since they are used in a url string. Makes booleans lower case since they are lower case in JSON. Also added test to check they both boolean cases as well as ints work properly.
=> duo_client says it accepts booleans, but fails on non-string input

duo_client/admin.py, tests/admin/test_admins.py
The new admin activation link creation endpoint is `POST /admin/v1/admins/activations`, instead of `POST /admin/v1/admins/activate`. I updated this end point with the relevant information about parameters and response information. 
Source from the docs [here](https://duo.com/docs/adminapi#create-administrator-activation-link).
=> Updated admin activation link endpoint

.travis.yml, tests/test_https_wrapper.py
Since python3.9 was released on Oct 5th 2020, it might be good to start running the test suite with that new version now.
=> Adding python3.9 to travis-ci config

duo_client/admin.py, duo_client/client.py, tests/admin/base.py, tests/admin/test_trust_monitor_events.py, tests/util.py
This PR adds a client call that allows users to pull Duo Trust Monitor events from the AdminAPI with a fairly basic set of parameters.  We are planning on adding actual documentation to this Duo Admin API endpoint before it goes GA.  Added a unittest to make sure that the parameters were correctly supplied.
=> Adding new endpoint to fetch trust monitor events from the admin api

README.md
Though pypi considers dashes and underscores in package names to be the same, in the case of `duo-client` the canonical name of the package is [`duo-client`](https://pypi.org/project/duo-client/) not `duo_client`.
When using a package management tool other than pip, for example an IDE, searching for duo_client won't return anything as the actual pypi package name is duo-client.
=> Correct pypi package name

.github/workflows/python-ci.yml
Python 3.9 was originally [released back in October 2020](https://docs.python.org/3/whatsnew/3.9.html).  Adding it to the github ci workflow so that CI is running all current versions.  Automated tests seemed to run as expected after observing the changes on my forked repo with 3.9 added.  This would be helpful in the event something specific in 3.9 suddenly breaks some of our tests.
=> Adding python3.9 to github ci workflow

duo_client/admin.py, tests/admin/test_endpoints.py
This was requested via [issue 136](https://github.com/duosecurity/duo_client_python/issues/136).  It's a small function that will let a user of the library fetch a single endpoint by a supplied epkey parameter.  Added a unittest to cover this new function and manually tested it on an actual Duo environment successfully.
I did notice that the the [documentation](https://duo.com/docs/adminapi#retrieve-endpoint-by-id) for this endpoint might be incorrect or I might be missing something else. Anyways, when I tested it locally the response from the api is a single endpoint dictionary object, but the documentation page says it's a list of a single endpoint dictionary object.
Please feel free to lmk if I should be changing anything else, thank you!
Fixes #136
=> Function to fetch a single endpoint object by epkey

examples/trust_monitor_events.py
Fixes #135
Adding example script of how to fetch recently-surfaced Duo Trust Monitor events from the Admin API.
=> Adding example script using the Duo Trust Monitor Events iterator

duo_client/client.py
Python's HTTPConnection already sets a `Host` header when connecting.
Don't set another as this is considered invalid by some HTTP servers.
=> Fixes #143: Remove extraneous `Host` header

duo_client/client.py
This is already otherwise fully plumbed. Tested with `nose2` and locally. Callers still need to indicate HTTP/HTTPS using the `ca_certs` mechanism. Untested with proxies, but looks like it should work...
=> Add port parameter to Client

.github/workflows/python-ci.yml
[Python 3.10 was released on October 4th, 2021](https://www.python.org/downloads/release/python-3100/) 🥳 🐍 🎈 so it might be beneficial to make sure that these automated tests w/ github actions are using that specific version moving forward.
=> Adding python3.10 to github automated tests

duo_client/client.py, tests/test_client.py
Fix logic for canonicalizing and signing requests using sig_version 4 by distinguishing between params and body in a backwards-compatible manner.
Add tests.
=> Fix Client for sig_version 4

.github/workflows/python-ci.yml
Drop testing for Python 2.7 and 3.5, add support for 3.11
=> Update tested python versions in CI

requirements-dev.txt
CI is failing when trying to build an old version of pytz, so just force it to use a current version
=> Force use of latest pytz version to fix CI

.github/workflows/python-ci.yml
Scheduled workflows get disabled after a period of inactivity, which also means they don't run on pushes or CI, which is not great.
=> Disable CI schedule

duo_client/client.py, tests/test_client.py
Updated client to use SHA2 signing for duo api calls.
Modified one sha test to pass successfully.
=> T159896: Updating SHA1 to SHA2

duo_client/admin.py
API call is described in https://duo.com/docs/adminapi#offline-enrollment-logs, but we didn't have a method for it
=> Add support for offline enrollment logs API call

duo_client/https_wrapper.py
Per https://docs.python.org/3/library/ssl.html:
```
ssl.PROTOCOL_TLS
Selects the highest protocol version that both the client and server support. Despite the name, this option can select both “SSL” and “TLS” protocols.
New in version 3.6.
```
```
ssl.PROTOCOL_SSLv23
Alias for [PROTOCOL_TLS](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS).
Deprecated since version 3.6: Use [PROTOCOL_TLS](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS) instead.
```
so there should be no functional change with this update, which we can make now that we don't support 3.5 or earlier.
=> Replace deprecated constant PROTOCOL_SSLv23 with PROTOCOL_TLS

duo_client/admin.py, duo_client/client.py, examples/create_integration_sso_generic.py, tests/accountAdmin/test_billing.py, tests/admin/test_admins.py, tests/admin/test_groups.py, tests/admin/test_integration.py, tests/admin/test_integrations.py, tests/admin/test_logo.py, tests/admin/test_settings.py, tests/admin/test_users.py, tests/test_client.py
This reintroduces a PR that was reverted due to a server-side bug. The only changes were simplifying some sig_version logic in the clients and fixing tests against master.
This PR is doing three things:
- Adding signature v5 support to the duo client
- Updates all calls in admin.py to use sig v5
- Updates all calls for get, create, update, and delete methods for integrations in admin.py to use the new v2 path and adds a new optional parameter of `sso`
=> Resubmit "Add sig_v5 support to duo_client_python calls and v2 integrations handler"

duo_client/admin.py, examples/policies.py, tests/admin/test_policies.py
Adding the following policy api v2 helper methods to `duo_client.Admin`:
1. `duo_client.Admin.get_policies_v2_iterator`.
2. `duo_client.Admin.get_policies_v2`.
3. `duo_client.Admin.delete_policy_v2`.
4. `duo_client.Admin.update_policy_v2`.
5. `duo_client.Admin.create_policy_v2`.
6. `duo_client.Admin.get_policy_v2`.
=> Adding policy v2 helpers & example script

duo_client/https_wrapper.py, tests/test_https_wrapper.py
Connecting to a service that uses SSL/TLS with SNI, for example AWS CloudFront, raises an `SSLV3_ALERT_HANDSHAKE_FAILURE` exception. To fix this, pass server hostname to `SSLContext.wrap_socket`.
=> Support SNI in duo client

duo_client/admin.py, duo_client/client.py, tests/test_client.py, tests/util.py
#201 Raised an issue where metadata might exist as either a sibling to `response` on the top-level object or inside of a `response` object. This adds support for either convention to `duo_client_python` along with additional tests for the alternate placement.
=> Add support for alternative metadata placement when paging

README.md
As title. 3.7 is the lowest python version that ci tested with
=> Add minimun python requirement

duo_client/client.py, tests/test_client.py
Fixes #219 by checking for a `dict` before attempting to use `get` to fetch the metadata from inside of a response object.
=> Fix issue parsing API responses that are just a string

duo_client/admin.py, duo_client/auth_v1.py, duo_client/client.py, tests/test_client.py
This makes the default sig_version for the duo client version 5 and only keeps version 2 for AuthV1.
=> Make sig_version 5 the default signature method for the client

.github/actions/sbom-convert/action.yml, .github/workflows/publish.yml, MANIFEST.in
Add automatic SBOM generation to releases generated by github actions.
This will eventually be added to many repos, so the SBOM conversion is separated into a separate action which can be reused by other repos.
Improved transparency on dependency versions and licenses.
This is a bit tricky. The majority of the action has been tested by creating releases on forks https://github.com/jeffreyparker/duo_client_python/actions/runs/5391813505 , but a full end-to-end test isn't possible until a real release is created.
=> SBOM composite action workflow

duo_client/admin.py
Creation of bypass codes now supports preservation of existing bypass codes. Parameter added to function that generates bypass codes in order to support this new functionality.
https://duo.com/docs/adminapi#create-bypass-codes-for-user
=> Added preserve_existing opt to adding bypass codes

examples/policies.py
We have made changes to the policy api so that it starts to return and accept a new field for the name: "policy_name" vs "name".  We will eventually completely remove "name", but this is just a tiny diff to update the example code.  There are no changes needed to the actual package itself.
Feedback from design / adp customers.
I've run the example code successfully on an actual duo deployment and it works as expected.
=> Update policy examples with "policy_name" vs "name"

setup.cfg
Our build config file set the universal flag which indicates both Py2 and Py3 support - but we haven't supported Py2 for a while, so remove that.
To correctly label the wheel file as Py3 only
Tested locally
=> Stop claiming Py2 support in wheel

setup.cfg
Remove a reference to Py2 in the build config since we don't support Py2 anymore
To accurately represent our Python support
N/A just a comment
=> Remove reference to Py2 in the bdist build config

duo_client/admin.py, examples/policies.py, tests/admin/test_policies.py
Add support for the bulk policy copy and update endpoints. 
Updates python client to support all endpoints for the policy admin API. 
Added new tests, updated the existing policy example, tested in dev environment.
=> Add methods for bulk policy operations

duo_client/admin.py, tests/admin/test_verification_push.py
Adds client methods for verification push methods
To make the Admin API verification push endpoints easier to use
Added tests
=> feat: Add verification push methods to client

duo_client/admin.py, tests/admin/test_settings.py
Add support unenrolled user lockout setting to adminapi settings [modify endpoint](https://duo.com/docs/adminapi#modify-settings)
- Paired changes 
Admins can adjust the same settings via Admin API as they can via Admin Panel
- Added utest
- Manual verification
=> Add unenrolled user lockout setting to adminapi

tests/accountAdmin/base.py
I don't know _why_ this suddenly started failing, but during the AccountAdmin tests, it looks like AccountAdmin init is trying to really reach out to the API to fetch the child accounts. This pre-populates child_api_host so it doesn't make a request.
I don't know that this is necessarily the _correct_ fix (e.g. vs ensuring that HTTP call is mocked), but it is _a_ fix.
Fix the automated tests
Tests now pass
=> Add child_api_host to AccountAdmin tests to fix failing tests

duo_client/admin.py, tests/accountAdmin/base.py
remove ssl certificate test failure bug - no longer accessing the real example.com
Factor out the code that causes the issue into a function and mock that function in the test cases.  Also, remove the temporary workaround.
https://cisco-sbg.atlassian.net/browse/ZTMSP-771
context: https://duosecurity.slack.com/archives/CJCHMJDL7/p1707334317810179 
ran nose2 with and without the changes in base.py - without the mocks (and the temporary workaround has been removed) 5 test cases fail.  They pass with the mock.
=> fix accessing real example.com in test cases

examples/Admin/report_user_activity.py
Remove Admin API test credentials mistakenly left in the report_user_activity.py example
Although the API credentials are no longer valid, the script would not execute as expected without the normal user input prompts from the terminal.
Verified expected execution manually.
=> chore: remove admin API credentials from report_user_activity example

duo_client/auth.py
In order to support verified push in auth API, we need to include these new parameters
to support the Verified Push in the Auth API
Yes tested via this script https://github.com/cisco-sbg/ZT-trustedpath/pull/7053
=> Add txid in auth and client_supports_verified_push in preauth

duo_client/admin.py, tests/admin/test_settings.py
Adds `enrollment_unversal_prompt_enabled` field to the admin settings endpoint
included the new field that can be set and returned when calling the admin settings endpoint
We recently added the new field to adminapi openapi spec. The changes here are updating our settings endpoint to match the spec.
`enrollment_universal_prompt_enabled:
description: >
If true, email enrollment will use the Universal Prompt experience.
If false, email enrollment will use the traditional Prompt experience.
type: boolean`
updated `test_update_settings()` in `test_settings.py` to include the new field
=> add enrollment_unversal_prompt_enabled to admin api settings

duo_client/admin.py
"detections" and "assessment" added to `VALID_AUTHLOG_REQUEST_PARAMS`
These are new filter keys that can be used while querying for authlogs. 
"detections" filters on specific Risk-based Remembered Devices detections and Risk-based Factor Selection detections.
"assessment" filters on the effective Risk-based Authentication trust assessment result.
This information is displayed in the authlog report UI, so Kit should have the ability to filter on them through the admin API.
This was tested on the "RBA Sandbox" customer in the First environment (changes to include these filters are rolling out with D287).
=> Add detections + assessment filter keys to valid authlog request params

.github/workflows/publish.yml
This fixes a version incompatibility in our SBOM workflow.  See https://github.com/duosecurity/duo_universal_python/pull/25 for the analogous PR to duo_universal_python
SBOM step is broken due to a major version incompatibility with the existing CLI invocation
Same fix as duo_universal_python
=> Pin cyclonedx dependency version

examples/Admin/policies.py, examples/Admin/policies_advanced.py
The device_health_app section of the policy API was updated to duo_desktop, with one variable renamed (requires_DHA -> requires_duo_desktop) last year, but the two policy examples that use it were not updated alongside it. This PR updates those two values, and also renames the functions that use them to say Duo Desktop instead of Device Health App.
This ensures that the current example for Duo Desktop policy is accurate and reflects the name change the Device Health App had last year.
Ran both policies and policies_advanced locally to ensure the policy was created correctly and updated with the correct Duo Desktop policies in my admin panel UI
=> Updating policy files to reflect the current Duo Desktop policy structure

duo_client/admin.py
Added a get_secret_key method to retrieve integration secret key from Admin API
Added a method in admin.py to make calls to the /admin/v1/integrations/[integration_key]/skey endpoint. 
Despite the documentation indicating this functionality is available and the Admin API providing the correct endpoint it is not currently implemented in the code. I am developing a script to automate the creation of new application integrations and programmatically store them in our organization's secret management solution. When testing the create_integration method I found that it returned all the necessary info except the secret key, when done in this way the secret is obfuscated and thus not suitable for my needs. 
Additionally, this will address issue #254.
Testing was completed by modifying a …
=> Added get_secret_key method to admin.py

duo_client/admin.py, tests/admin/test_passport.py
Tested-by: new test case in tests/test_passport.py
Add new get_passport_config() method to client.Admin to accommodate the recent addition to the Admin API
Ensure continued parity between the documented public Admin API endpoints and library functionality
New test case test_passport.py was added to validate the new method
=> feat: add get_passport_config() to client.Admin

duo_client/admin.py
Add a new parameter, endpoint_verification, to the bypass code creation endpoint.
This new parameter is needed as part of a feature that is currently in development.
The use of this parameter has been tested internally.
=> Update bypass code endpoint with new parameter

duo_client/admin.py, tests/accountAdmin/base.py
Two new examples for the Accounts API are proposed to illustrate both the extraction of existing application integrations from a child account via a parent account API as well as the creation of new application integrations in child accounts.
This addition is in response to consumer feedback regarding the need for additional examples and documentation.
These examples were test for both success and failure scenarios against internal Duo accounts.
=> Accounts API examples for interacting with child accounts via parent account APIs

duo_client/admin.py, tests/admin/test_registered_devices.py
feat: add registered_devices methods to client.Admin
Tested-by: new test case in tests/admin/test_registered_devices.py
Add new methods for administering Duo Desktop registered devices to the Admin client
Expand client library functionality to more closely match available API endpoints
Tested via new automated test cases defined in `tests/admin/test_registered_devices.py`
=> feat: add registered_devices methods to client.Admin

duo_client/admin.py
After the changes in the following PRs in file `third-party/duo_client_python/project/duo_client/admin.py`:
1. https://github.com/cisco-sbg/ZT-trustedpath/pull/15397/files
2. https://github.com/cisco-sbg/ZT-trustedpath/pull/16174/files 
We need to update the file `duo_client/admin.py` in duo_client_python as well. 
Ticket: https://cisco-sbg.atlassian.net/browse/ZTAEX-985
After the feature has gone GA, we should add the verified push setting to the duo client repo to ensure Kit can control it from duo_client_python 
All existing Admin tests should pass.
=> Update set_allowed_admin_auth_methods in admin.py

README.md, duo_client/admin.py, tests/admin/test_policies.py
Adds calculate policy endpoint to the admin client. Mirrors TP changes. 
Creates consistency with internal client.
Added itest in TP and utest here.
=> Adds calculate policy endpoint to admin client

duo_client/admin.py, tests/admin/test_passport.py
Create a method to call the API endpoint that creates or updates a customer's Passport configuration https://duo.com/docs/adminapi#passport
Make it easier for tools and automations to update the Passport configuration
Added a unit test to ensure arguments are passed correctly.
```
❯ nose2
........................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 216 tests in 0.140s
OK
```
Tested locally against a development server:
```
>>> client = duo_client.admin.Admin(ikey=..., skey=..., host="api-duo1.duo.test", ca_certs="DISABLE")
>>> client.get_passport_config() …
```
=> add method to update Passport configuration via the AdminAPI

duo_client/admin.py, tests/admin/test_integration.py, tests/admin/test_integrations.py
Updates references to `admin/v2/integrations` to `admin/v3/integrations`. The `v3` version of the endpoints adds a small breaking change to the integrations fields.
Updates references to `admin/v2/integrations` to `admin/v3/integrations` and adds handling for the new `user_access` field on create/update.
The `v3` endpoints add a new `user_access` field and changes the behavior of `groups_allowed`.
Previously the `groups_allowed` field by itself determined which users could authenticate with the application as described [here](https://duo.com/docs/adminapi#integrations). Now a third state has been added which allows _no_ users to authenticate.
Because of that, the `user_access` field has been added to express this more cleanly, and `groups_allowed` can only be provided if `user_access === …
=> Update integrations endpoints to v3

.github/workflows/python-ci.yml, duo_client/admin.py
This PR edits the comments in `duo_client_python/duo_client/admin.py` to show that `visual_style` parameter is deprecated.
Addresses issue #280.
N/A
=> Update comments to indicate visual_style param as deprecated

duo_client/admin.py, examples/Admin/create_user_and_phone.py
Ability to add custom attributes when creating a user
Yes, i have screenshots.
1. Using existing api without setting custom attributes
2. Api call succeeds and creates user with custom attribute
3. Api call when custom attribute doesn't exist
4. Incorrect map
=> add_user supports custom attributes
