duosecurity/duo_client_python

examples/create_user_and_phone.py, examples/report_users_and_phones.py, examples/splunk/splunk.py, examples/verify_phone_number_with_voice_call.py
=> Put shebang before imports.

duo_client/admin.py, examples/report_auths_by_country.py
Add comments and example script with addition of geoip location data to admin API
=> Geoip in auth example

duo_client/admin.py
=> Add helpdesk_bypass field to update_settings

duo_client/admin.py
=> Update admin.py to include "deny" helddesk_bypass option

duo_client/admin.py
security_checkup_enabled was added to the AdminAPI. This PR adds the functionality to duo_client to set the setting
=> Update admin.py to include security_checkup_enabled for the Security Checkup feature

duo_client/admin.py
We added support to update the settings for Duo Restore to the AdminAPI. This PR is to add the functionality to duo_client.
=> Update admin.py to include reactivation_url and reactivation_integration_key for Duo Restore

MANIFEST.in
Fix for https://github.com/duosecurity/duo_client_python/issues/36
=> Added requirements-dev.txt to MANIFEST.in to fix bdist_rpm

duo_client/admin.py, tests/test_admin.py, tests/util.py
Adds methods to get u2ftokens, get u2ftokens by user id, get a u2ftoken by registration id, and delete a u2ftoken by registration id. In addition, I have created tests for these new methods.
=> Add u2ftoken methods to Admin API

duo_client/admin.py, tests/test_admin.py
Renames the following methods in the admin class:
- get_user_bypass_codes --> **add_user_bypass_codes**: adds bypass codes for a user
Adds the following methods to the admin class:
- **get_user_bypass_codes**: gets all bypass codes belonging to a user
- **get_bypass_codes**: gets all bypass codes
- **delete_bypass_code_by_id**: deletes a bypass code by its id
=> Add bypass code methods to admin class.

duo_client/admin.py, tests/test_admin.py
Added support for firstname and lastname parameters for add_user() and update_user().
=> Added support for ID Proofing fields

duo_client/admin.py
Set an admin's password as needing to be changed on next login.
=> Add password_change_required to update_admin

duo_client/admin.py, tests/test_admin.py
Add pagination to the get_tokens method and tests to confirm behavior.
=> Add pagination to admin client get_tokens

duo_client/client.py, tests/test_client.py
This is something a lot of other diffs will depend upon.
=> Adds normalize paging args method.

duo_client/admin.py, tests/admin/test_users.py
Add method for the single user sync directory endpoints.
=> add sync_user to admin.Admin

README.md
I stumbled a bit on these development setup steps, and I noted they've tripped up at least one other person in #93 . Figured I could fill in some missing pieces.
=> explicitly add a few implied steps to the readme

duo_client/admin.py, tests/admin/test_user_webauthn.py, tests/admin/test_webauthn.py
Hey Guys,
i am using FIDO2 tokens with DUO and discovered that there is an undocumented webauthn-credentials API endpoint.
Looking forward to get this merged into upstream.
Thanks a lot.
=> Add methods and tests for webauthn-credentials.

duo_client/admin.py
Also cleaned up/standardized update_settings doc
=> Add support for updating helpdesk_message

duo_client/admin.py
Adding the ability to specify the "aliases" parameter detailed on https://duo.com/docs/adminapi#create-user and https://duo.com/docs/adminapi#modify-user
=> Added aliases param to add_user and update_user.

duo_client/admin.py, examples/splunk/splunk.py
Rename one variable and remove unused variables
=> bug fix for variables name

examples/splunk/splunk.py
remove one more unused variable
=> remove unused variables

duo_client/client.py
=> Version bump to 4.3.2

duo_client/client.py, tests/test_client.py
Remove logic for sig_version 3. Remove tests. Add test confirming sig_version 3 raises an exception.
=> Remove support for sig_version 3

README.md, duo_client/admin.py, examples/report_activity.py, requirements-dev.txt, tests/admin/base.py, tests/admin/test_activity.py, tests/util.py
Exposing the new activity endpoint
=> Adding new endpoint 

duo_client/client.py, tests/test_client.py
Added missed SHA512 conversion code and created a test in test_client.py for SHA512 signature
=> Completed SHA1 to SHA512 conversion in client.py

duo_client/client.py
=> Version bump for 4.6.0

duo_client/client.py
what title said. 
Don't merge until March 27
=> duo_client_python 4.7.0 version bump

duo_client/client.py
=> version bump to 5.0.0

duo_client/admin.py
Add `email_activity_notification_enabled` & `push_activity_notification_enabled` to modify customer settings method
=> Add device notification settings to adminapi

duo_client/admin.py, tests/admin/test_policies.py
Adds a new method `get_policy_summary_v2` for the `/admin/v2/policies/summary` endpoint
Gives access to new policy API endpoint. 
Added a new test, verified that the new endpoint works as expected.
=> Add policy summary endpoint

duo_client/client.py
Version bump for a 5.1.0 release
To release the bulk api parameter changes
N/A
Version bump only
=> Version bump to prep 5.1.0 release

.github/workflows/publish.yml
We were not installing the six dependency in the publish workflow
To fix the publish flow
N/A
=> Add six to dependencies for publish

duo_client/client.py
Version bump to 5.2.0 to prep release of some Accounts API and bulk Policy API work
Just a normal version bump
N/A
Version bump
=> 5.2.0 version bump

duo_client/admin.py, examples/report_user_by_email.py
Add get_user_by_email() method to duo_client_python. Also add script for example usage of new method.
Created in response to issue #231 
Execution of both manual positive and negative result example script execution against test Duo account.
=> Add get user by email method to duo_client_python along with example script

duo_client/client.py
Version bump in preparation for release
Minor version bump so we can release some new functionality
tests/ci pass
=> Bump version in Client.py to 5.3.0

.github/workflows/python-ci.yml
What the title says.
Python 3.7 isn't available on ubuntu anymore.
N/A
=> Update Python versions in CI

duo_client/client.py
Version bump in preparation for release
=> Version bump to 5.4.0

duo_client/client.py
=> Version bump to 5.5.0

examples/Auth/basic_user_mfa.py
In addition to the ipaddr param, this also introduces argparse to organize args better.
I wanted to test the preauth and auth APIs with the `ipaddr` field specified.
Ran the example client, pointed at a test Duo instance. Saw ipaddr populated in authlogs.
=> Enable setting ipaddr param in preauth and auth
